"""create event_queue model

Revision ID: 7613873a8549
Revises: 8f0601abbc5c
Create Date: 2026-06-21 17:49:08.559465

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '7613873a8549'
down_revision: Union[str, None] = '8f0601abbc5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_queues',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('playlist_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('event', postgresql.ENUM('play', 'pause', 'add', 'skip', 'move', name='playlist_event_type'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], name=op.f('fk_event_queues_playlist_id_playlists'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['track_id'], ['playlist_track.id'], name=op.f('fk_event_queues_track_id_playlist_track'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_event_queues_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_queues'))
    )
    op.create_index('idx_event_queues_created_at', 'event_queues', ['created_at'], unique=False)
    op.create_index('idx_event_queues_playlist_id', 'event_queues', ['playlist_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_event_queues_playlist_id', table_name='event_queues')
    op.drop_index('idx_event_queues_created_at', table_name='event_queues')
    op.drop_table('event_queues')
    # ### end Alembic commands ###
