"""create playlist track model

Revision ID: 8f0601abbc5c
Revises: 7666f6b1e613
Create Date: 2026-06-20 19:48:25.087546

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '8f0601abbc5c'
down_revision: Union[str, None] = '7666f6b1e613'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlist_track',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('track_info_id', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('status', postgresql.ENUM('played', 'queued', 'playing', name='track_playback_status'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.CheckConstraint('position > 0', name=op.f('ck_playlist_track_chk_positive_position')),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], name=op.f('fk_playlist_track_playlist_id_playlists'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_playlist_track_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_playlist_track')),
    sa.UniqueConstraint('playlist_id', 'position', name='uq_playlist_position')
    )
    op.create_index('idx_playlist_track_query', 'playlist_track', ['playlist_id', 'position'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_playlist_track_query', table_name='playlist_track')
    op.drop_table('playlist_track')
    # ### end Alembic commands ###
