"""create device table

Revision ID: 943455df7c96
Revises: 1fc83f47fb6c
Create Date: 2026-08-29 14:33:07.162019

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '943455df7c96'
down_revision: Union[str, None] = '1fc83f47fb6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_devices_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices'))
    )
    op.create_table('device_delegations',
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('delegate_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['delegate_user_id'], ['users.id'], name=op.f('fk_device_delegations_delegate_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_device_delegations_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('device_id', 'delegate_user_id', name=op.f('pk_device_delegations'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device_delegations')
    op.drop_table('devices')
    # ### end Alembic commands ###
