"""create friend_requests table

Revision ID: 98666eda869e
Revises: f7aeb1a9a555
Create Date: 2026-08-08 22:22:38.489721

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '98666eda869e'
down_revision: Union[str, None] = 'f7aeb1a9a555'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friend_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.UUID(), nullable=False),
    sa.Column('addressee_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'declined', name='friend_request_status'), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('requester_id != addressee_id', name=op.f('ck_friend_requests_ck_friend_requester_not_addressee')),
    sa.ForeignKeyConstraint(['addressee_id'], ['users.id'], name=op.f('fk_friend_requests_addressee_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], name=op.f('fk_friend_requests_requester_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_friend_requests')),
    sa.UniqueConstraint('requester_id', 'addressee_id', name='uq_friend_requester_addressee')
    )
    op.create_index(op.f('ix_friend_requests_addressee_id'), 'friend_requests', ['addressee_id'], unique=False)
    op.create_index(op.f('ix_friend_requests_id'), 'friend_requests', ['id'], unique=False)
    op.create_index(op.f('ix_friend_requests_requester_id'), 'friend_requests', ['requester_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_friend_requests_requester_id'), table_name='friend_requests')
    op.drop_index(op.f('ix_friend_requests_id'), table_name='friend_requests')
    op.drop_index(op.f('ix_friend_requests_addressee_id'), table_name='friend_requests')
    op.drop_table('friend_requests')
    # ### end Alembic commands ###
