"""create users table

Revision ID: 9d575745bbb9
Revises: 
Create Date: 2026-04-27 18:44:43.708218

"""

from typing import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa


revision: str = '9d575745bbb9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
