"""create track info

Revision ID: b0dacb96408c
Revises: 29fd3d2d0fd7
Create Date: 2026-07-09 19:16:14.120303

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b0dacb96408c'
down_revision: Union[str, None] = '29fd3d2d0fd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('track_info',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('channel_title', sa.String(length=255), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=512), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_track_info'))
    )
    op.create_index(op.f('ix_track_info_id'), 'track_info', ['id'], unique=False)
    op.alter_column('playlist_track', 'track_info_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=32),
               nullable=False)
    op.create_foreign_key(op.f('fk_playlist_track_track_info_id_track_info'), 'playlist_track', 'track_info', ['track_info_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_playlist_track_track_info_id_track_info'), 'playlist_track', type_='foreignkey')
    op.alter_column('playlist_track', 'track_info_id',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('ix_track_info_id'), table_name='track_info')
    op.drop_table('track_info')
    # ### end Alembic commands ###
