"""remove track_info from events

Revision ID: b4ae3edf2903
Revises: fc3a71dd8db5
Create Date: 2026-07-08 18:08:24.380843

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b4ae3edf2903'
down_revision: Union[str, None] = 'fc3a71dd8db5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_queues', 'track_info_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_queues', sa.Column('track_info_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
