"""fix wrong relationship

Revision ID: bdfd0738d015
Revises: 7613873a8549
Create Date: 2026-06-26 22:02:34.248442

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bdfd0738d015'
down_revision: Union[str, None] = '7613873a8549'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_queues', sa.Column('track_info_id', sa.String(length=255), nullable=True))
    op.drop_constraint(op.f('fk_event_queues_track_id_playlist_track'), 'event_queues', type_='foreignkey')
    op.drop_column('event_queues', 'track_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_queues', sa.Column('track_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_event_queues_track_id_playlist_track'), 'event_queues', 'playlist_track', ['track_id'], ['id'], ondelete='SET NULL')
    op.drop_column('event_queues', 'track_info_id')
    # ### end Alembic commands ###
