"""make constraint deferrable

Revision ID: fc3a71dd8db5
Revises: fec6e5b3271c
Create Date: 2026-06-27 18:13:53.487657

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fc3a71dd8db5'
down_revision: Union[str, None] = 'fec6e5b3271c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_playlist_position', 'playlist_track', type_='unique')
    
    op.create_unique_constraint(
        'uq_playlist_position', 
        'playlist_track', 
        ['playlist_id', 'position'],
        deferrable=True, 
        initially='DEFERRED'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_playlist_position', 'playlist_track', type_='unique')
    op.create_unique_constraint(
        'uq_playlist_position', 
        'playlist_track', 
        ['playlist_id', 'position']
    )
    # ### end Alembic commands ###
