"""remove positive constraint

Revision ID: fec6e5b3271c
Revises: bdfd0738d015
Create Date: 2026-06-27 17:57:50.655464

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fec6e5b3271c'
down_revision: Union[str, None] = 'bdfd0738d015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chk_positive_position', 'playlist_track', type_='check')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        'chk_positive_position', 
        'playlist_track', 
        'position > 0'
    )
    # ### end Alembic commands ###
