import uuid
from datetime import datetime

from pydantic import BaseModel, ConfigDict, Field


class DeviceCreate(BaseModel):
    id: uuid.UUID = Field(
        ...,
        description="The unique hardware or installation ID generated by the client",
    )
    name: str = Field(
        default="My Device",
        max_length=100,
        description="A friendly name for the device",
    )


class DeviceRead(BaseModel):
    id: uuid.UUID
    owner_id: uuid.UUID
    name: str
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)
