name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - development

jobs:
  basic-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: test -d specs
      - run: find specs -maxdepth 3 -type f